# Generated by Django 5.0.6 on 2024-05-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('commune_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('enduser_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('garage_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_garage', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('gerant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_gerant', models.CharField(max_length=255)),
                ('prenom_gerant', models.CharField(max_length=255)),
                ('type_gerant', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.garage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('quartier_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_quartier', models.CharField(max_length=255)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.commune')),
            ],
        ),
        migrations.AddField(
            model_name='garage',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.quartier'),
        ),
        migrations.CreateModel(
            name='Remorquage',
            fields=[
                ('remorquage_id', models.AutoField(primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=255)),
                ('demande_date', models.DateField()),
                ('re_description', models.CharField(max_length=255)),
                ('besoin_auto', models.CharField(max_length=255)),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.enduser')),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.gerant')),
            ],
        ),
        migrations.AddField(
            model_name='garage',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depannagexpressapp.utilisateur'),
        ),
    ]
