# Generated by Django 5.0.6 on 2024-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depannagexpressapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("depart", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("details", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
